version: 1
db:
  user: sb
  passwd: sb
  name: pictest
  # name: npix
  host: 127.0.0.1
  port: 5432

ui:
  # Specify window geometry <width>x<height>+<x-offset>+<y-offset>
  geometry: 2500x1200+10+10

cache:
  # Maximum size of LRU caches.
  # Zero or negative number gives unlimited cache size.
  tags: -1
  pictures: -1
  groups: -1

trace:
  # configure method tracing: will create massive files and slow down the app.
  activate: False
  trace_file: /Users/sb/.picdb/trace.txt
