version: 1
# database: /Volumes/B3T/data_sets/pixdb.db
# database: /Volumes/stories/picdb.db
database: /Users/sb/Development/projects/picdb/test.db

# Specify window geometry <width>x<height>+<x-offset>+<y-offset>
geometry: 2200x1000+100+100
