version: 1
# DEBUG - INFO - WARNING - ERROR
formatters:
  simple:
    format: '%(asctime)s %(name)s %(levelname)s %(filename)s %(funcName)s():%(lineno)d - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: /Users/sb/.picdb/picdb.log
    maxBytes: 10000000
    backupCount: 3
loggers:
  picdb:
    level: WARNING
    handlers: [console, file]
    propagate: no
  picdb.db:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  picdb.ui:
    level: WARNING
    handlers: [console, file]
    propagate: no
  picdb.config:
    level: WARNING
    handlers: [console, file]
    propagate: no
  picdb.logging:
    level: WARNING
    handlers: [console, file]
    propagate: no
root:
    level: WARNING
    handlers: [console, file]
