version: 1
db:
  user: sb
  passwd: sb
  name: pictest
  host: 127.0.0.1
  port: 5432

ui:
  # Specify window geometry <width>x<height>+<x-offset>+<y-offset>
  geometry: 2500x1200+10+10

cache:
  tags: 2000
  pictures: 100000
  groups: 2000
