version: 1
# DEBUG - INFO - WARNING - ERROR
formatters:
  simple:
    format: '%(asctime)s %(name)s %(levelname)s %(filename)s %(funcName)s():%(lineno)d - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  picdb:
    level: WARNING
    handlers: [console]
    propagate: no
  picdb.db:
    level: WARNING
    handlers: [console]
    propagate: no
  picdb.ui:
    level: WARNING
    handlers: [console]
    propagate: no
  picdb.config:
    level: WARNING
    handlers: [console]
    propagate: no
  picdb.logging:
    level: WARNING
    handlers: [console]
    propagate: no
root:
  level: WARNING
  handlers: [console]
